site:
  name: 'Fynn'
  site: 'https://fynn.ai'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: false

metadata:
  title:
    default: 'Fynn - AI-Powered Debt Collection Solutions'
    template: '%s — Fynn'
  description: >-
    Transform your accounts receivables with Fynn's AI-powered debt collection solutions.
    Efficient, transparent, and customer-centric approach for modern businesses.
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Fynn'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@fynnai'
    site: '@fynnai'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: true
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Replace with your Google Analytics ID
      partytown: true

ui:
  theme: 'system'